### ISSUE TITLE
File location confusion

### ISSUE THREAD

**Issue by domenic** [GoogleChromeLabs/kv-storage-polyfill#1]
The repository has a src/ directory with .js files

The distributed package has a dist/ directory with .js and .mjs files

The README suggests using `/node_modules/kv-storage/index.mjs` which exists in neither case.

What's the plan?

**Comment by developit** [comment]
Ah - need to modify the readme.

**Comment by developit** [comment]
Readme modified for now, but it'd be nice to get rid of `dist`.
